Revert "use __dead macro from sys/cdefs.h"
This partially reverts commit a7577667d673f49800e15461fe384817a1572eae.

The musl C library does not use an internal cdefs.h header. As a result,
the definitions in sys/cdefs.h have no effect. This breads the build as
follows:

In file included from adjfreq_linux.c:23:0:
../src/ntpd.h:448:8: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 __dead void fatal(const char *, ...)
        ^~~~
../src/ntpd.h:450:8: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 __dead void fatalx(const char *, ...)
        ^~~~

Refer the related musl FAQ about cdefs.h:

  http://wiki.musl-libc.org/wiki/FAQ#Q:_I.27m_trying_to_compile_something_against_musl_and_I_get_error_messages_about_sys.2Fcdefs.h

Keep the compiler attribute definition.

Remove also from noinst_HEADERS.